#include <iostream>
#include <stdlib.h>
#include <vector>
#include <algorithm>
 

int main() {
// Initialize a vector with 10 ints of value 0
	std::vector<int> vecOfRandomNums(10);
 
// Generate 10 random numbers by lambda func and fill it in vector
	std::generate(vecOfRandomNums.begin(), vecOfRandomNums.end(), []() {
		return rand() % 100;
	});
 
	std::cout << "Random Number Generated by Lambda Function" << std::endl;
	for (int val : vecOfRandomNums)
		std::cout << val << std::endl;
 
	return 0;
}